# -*- coding: utf-8 -*-
"""Grading_Program

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aiJHZvXVmvSm4qD29WQDQZzh-wWpCk2B
"""

import pandas as pd  # Package to work with data

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

df = pd.read_csv('input.csv')

mean = df.mean(axis="columns")

df["Average"] = mean.round(1)

df['Grade'] = pd.cut(df['Average'], bins=[0, 39.9, 49.9 , 59.9 , 69.9 , 79.9, 100 ], labels= ['F', 'E', 'D', 'C', 'B', 'A'])

copy_list = ['Firstname', ' Surname' , 'Average' , "Grade"]
dffinal= df[copy_list].copy()

dffinal.loc[10] = ["Seth" , "Volson" , 90, "A" ] 

dffinal.to_csv('output.csv') 
files.download('output.csv')




